name: ns_firebase_utils
description: This package provides a comprehensive set of methods and extensions for Firebase, simplifying its integration into your Flutter projects while also adding valuable functionality.
version: 1.1.3
homepage: https://github.com/ProjectAJ14/ns_firebase_utils

environment:
  sdk: '>=2.17.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # cloud_firestore: ^4.17.5
  # cloud_functions: ^4.5.0
  # fake_cloud_firestore: ^2.4.4
  # firebase_analytics: ^10.6.0
  # firebase_auth: ^4.11.0
  # firebase_core: ^2.32.0
  # firebase_crashlytics: ^3.4.0
  # firebase_dynamic_links: ^5.4.0
  # firebase_messaging: ^14.7.0
  # firebase_remote_config: ^4.3.0
  # firebase_storage: ^11.3.0
  cloud_firestore: ^4.17.5
  cloud_functions: ^4.5.0
  fake_cloud_firestore: ^2.4.4
  firebase_analytics: ^10.10.7
  firebase_auth: ^4.11.0
  firebase_core: ^2.32.0
  firebase_crashlytics: ^3.4.0
  firebase_dynamic_links: ^5.4.0
  firebase_messaging: ^14.7.0
  firebase_remote_config: ^4.3.0
  firebase_storage: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
